### ISSUE TITLE
Not an issue but a few questions

### ISSUE THREAD

**Issue by greenreader9** [m7md3omer/ecommerce-laravel-fullstack#30]
1. How is payment processed? (Stripe, PayPal, etc.) On the checkout page, I don't see all the details that would be needed for credit card billing.
2. Can an option be made on the checkout page to create a new account so the order is saved for the customer?

Thanks!

**Comment by Abdullah-Pele** [comment]
how can I add payment methods to my website ??

**Comment by mhmdomer** [comment]
Hey @greenreader9 
1. The provided payment processor here is stripe, the code is commented out so that it won't send an actual or fake payment to stripe when users are testing the app.
Feel free to add your own payment method
2. When you put items on the cart, it is saved on the session, so if you created an account after placing items on the cart it should be persisted and saved on your newly created account.
